In [50]:
import numpy as np

### Задача 1
Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:
а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;
б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;
в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;
г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;
AB - не определено
BA - не определено

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;
AB - 2 *3
BA - не определено

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;
AB - 8 * 8
BA - 3 * 3

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .
AB - 4 * 4
BA - 4 * 4

### Задача 2
Найти сумму и произведение матриц
A

---|---
1  | -2
3  |  0

B

---|---
4  | -1
0  |  5

In [51]:
a1 = np.array([[1, -2],
               [3, 0]])

b1 = np.array([[4, -1],
               [0, 5]])

sum = np.array([[1 + 4, (-2) + (-1)],
                [3 + 0, 0 + 5]])

prod = np.array([[1 * 4 + (-2) * 0,
                  1 * (-1) + (-2) * 5],
                 [3 * 4 + 0 * 0,
                  3 * (-1) + 0 * 5]])

print(f'Сумма матриц \n{sum}')
print(f'Произведение матриц \n{prod}')

Сумма матриц 
[[ 5 -3]
 [ 3  5]]
Произведение матриц 
[[  4 -11]
 [ 12  -3]]


### Задача 3
Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство.
Вычислить линейную комбинацию  3A−2B+4C  для матриц
A

---|---
1  | 3
7  |  -6

B

---|---
0  | 2
5  |  -1

C

---|---
2  | -4
1  |  1

In [52]:
a2 = np.array([[1, 3],
               [7, -6]])

b2 = np.array([[0, 5],
               [2, -1]])

c2 = np.array([[2, -4],
               [1, 1]])

a_mul3 = np.array([[1 * 3, 3 * 3],[7 * 3, -6 * 3]])
b_mul2 = np.array([[0 * 2, 5 * 2],[2 * 2, -1 * 2]])
c_mul4 = np.array([[2 * 4, -4 * 4],[1 * 4, 1 * 4]])


a_mul3_sub_b_mul2_sum_c_mul4 = np.array([[(1 * 3) - (0 * 2) + (2 * 4), (3 * 3) - (5 * 2) + (-4 * 4)],
                                         [(7 * 3) - (2 * 2) + (1 * 4), (-6 * 3) - (-1 * 2) + (1 * 4)]])

print(f'3A−2B+4C =\n {a_mul3_sub_b_mul2_sum_c_mul4}')

3A−2B+4C =
 [[ 11 -11]
 [ 15 -12]]


In [53]:
a_mul3 - b_mul2 + c_mul4

array([[ 11, -11],
       [ 15, -12]])

### Задача 4
Дана матрица
A=

---|---
4  | 1
5  |  -2
2  | 3

Вычислить  AA^T^  и  A^T^A

In [54]:
a3 = np.array([[4, 1],
               [5, -2],
               [2, 3]])

a3t = np.array([[4, 5, 2],
                [1, -2, 3]])

a3_mul_a3t = np.array([[4 * 4 + 1 * 1,
                        4 * 5 + 1 * (-2),
                        4 * 2 + 1 * 3],
                       [5 * 4 + (-2) * 1,
                        5 * 5 + (-2) * (-2),
                        5 * 2 + (-2) * 3],
                       [2 * 4+ 3 * 1,
                        2 * 5+ 3 * (-2),
                        2 * 2+ 3 * 3]])

a3t_mul_a3 = np.array([[4 * 4 + 5 * 5 + 2 * 2,
                        4 * 1 + 5 * (-2) + 2 * 3],
                       [1 * 4 + (-2) * 5 + 3 * 2,
                        1 * 1 + (-2) *  (-2) + 3 *3]])

print(f'Произведение матрицы А на транспонированную А\n{a3_mul_a3t}')
print(f'Произведение транспонированной матрицы А на А\n{a3t_mul_a3}')

Произведение матрицы А на транспонированную А
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Произведение транспонированной матрицы А на А
[[45  0]
 [ 0 14]]
