In [13]:
import numpy as np

### Задача 1
Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей

$$A=\begin{pmatrix}
-1 & -6\\
2 & 6
\end{pmatrix}.$$

In [14]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

print(f'Собственные векторы\n{v}')
print(f'Собственные значения\n{w}')

Собственные векторы
[[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]
Собственные значения
[2. 3.]


### Задача 2
Дан оператор поворота на 180 градусов, задаваемый матрицей

$$
{A=\begin{pmatrix}
-1 & 0\\
0 & -1
\end{pmatrix}.
$$

Показать, что любой вектор является для него собственным.


характеристическое уравнение для любого вектора и данного оператор будет равно
\begin{equation*}
 \begin{cases}
   -x = $\lambda\ * x,
   \\
   -y = $\lambda\ * y,
 \end{cases}
\end{equation*}

то lambda  = -1
следовательно любой не нулевой вектор (а собственные вектора не могут быть нулевыми) будет иметь решение, а следовательно - любой вектор собственный

### Задача 3
Пусть линейный оператор задан матрицей

$$
{A=\begin{pmatrix}
1 & 1\\
-1 & 3
\end{pmatrix}.
$$

Установить, является ли вектор  x=(1,1)  собственным вектором этого линейного оператора.

In [15]:
a = np.array([[-1, -6], [2, 6]])
x = np.array([1, 1])

a.dot(x)

array([-7,  8])

т.к. система

\begin{equation*}
 \begin{cases}
   -7 = $\lambda\,
   \\
   8 = $\lambda\,
 \end{cases}
\end{equation*}

не имеет решений, то вектор x=(1, 1) не является собственным

### Задача 4
Пусть линейный оператор задан матрицей

$$
\begin{flushleft}
{A=\begin{pmatrix}
0 & 3 & 0\\
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\end{flushleft}
$$

Установить, является ли вектор  x=(3,−3,−4)  собственным вектором этого линейного оператора.

In [16]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
x = np.array([3, -3, -4])

a.dot(x)

array([ -9,   9, -12])

т.к. решением системы

\begin{equation*}
 \begin{cases}
   -9 = 3 * $\lambda\,
   \\
   9 = -3 * $\lambda\,
   \\
   -12 = 4 * $\lambda\,
 \end{cases}
\end{equation*}

 является -3, то вектор x=(3,−3,−4) является собственным вектором