In [11]:
import numpy as np

### Задание 1
Найти с помощью NumPy SVD для матрицы
$$\begin{pmatrix}
1 & 2 & 0\\
0 & 0 & 5\\
3 & -4 & 2\\
1 & 6 & 5\\
0 & 1 & 0
\end{pmatrix}.$$



In [16]:
A = np.matrix([[1, 2, 0],
               [0, 0, 5],
               [3, -4, 2],
               [1, 6, 5],
               [0, 1, 0]])

U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

print(np.round(np.dot(np.dot(U, D), V.T)))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


### Задание 2
Для матрицы из предыдущего задания найти:
а) евклидову норму;
б) норму Фробениуса.

In [13]:
evkl = D.A[0][0]
print(f'Норма Евклида равна {evkl}')

Норма Евклида равна 8.824868854820444


In [14]:
fro = np.linalg.norm(A, 'fro')
print(f'Норма Фробениуса равна {fro}')

Норма Фробениуса равна 11.045361017187261
