In [156]:
import numpy as np

### Задача 1
Решить систему уравнений методом Крамера:

In [157]:
def kramer(base_m, free_members):
    eps = 0.0000000001
    if base_m.shape[0] != base_m.shape[1]:
        raise Exception ('Матрица не квадратная')

    detA = np.linalg.det(base_m)
    res = []
    if detA and detA > eps:
        for col in range(0, base_m.shape[1]):
            A_ = base_m.copy()
            A_[:, col] = free_members
            detA_ = np.linalg.det(A_)
            common_res = round(detA_ / detA, 5)
            res.append(common_res)
    return res

а) $\begin{cases} x_{1}-2x_{2}=1 \\ 3x_{1}-4x_{2}=7 \end{cases}$

In [158]:
A =np.array([[1, -2],
             [3, -4]])
b = np.array([1, 7])

kramer_res = kramer(A, b)
print(f'Частные решения системы методом Крамера {kramer_res}')

Частные решения системы методом Крамера [5.0, 2.0]


б) $\begin{cases} 2x_{1}-x_{2}+5x_{3}=10 \\ x_{1}+x_{2}-3x_{3}=-2 \\ 2x_{1}+4x_{2}+x_{3}=1 \end{cases}$

In [159]:
A =np.array([[2, -1, 5],
             [1, 1, -3],
             [2, 4, 1]])
b = np.array([10, -2, 1])

kramer_res = kramer(A, b)
print(f'Частные решения системы методом Крамера {kramer_res}')

Частные решения системы методом Крамера [2.0, -1.0, 1.0]


### Задача 2
Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

In [160]:
def solve_LU(lu_matrix, b):
    """Solve system of equations from given LU-matrix and vector b of absolute terms.
    :param lu_matrix: numpy LU-matrix
    :param b: numpy matrix of absolute terms [n x 1]
    :return: numpy matrix of answers [n x 1]
    """
    n = lu_matrix.shape[0]
    # get supporting vector y
    y = np.matrix(np.zeros([n, 1]))
    for i in range(y.shape[0]):
        y[i, 0] = b[i, 0] - lu_matrix[i, :i] * y[:i]

    # get vector of answers x
    x = np.matrix(np.zeros([n, 1]))
    for i in range(1, x.shape[0] + 1):
        x[-i, 0] = (y[-i] - lu_matrix[-i, -i:] * x[-i:, 0] )/ lu_matrix[-i, -i]

    return x

In [161]:
def decompose_to_LU(a):
    """Decompose matrix of coefficients to L and U matrices.
     L and U triangular matrices will be represented in a single nxn matrix.
    :param a: numpy matrix of coefficients
    :return: numpy LU matrix
    """
    # create emtpy LU-matrix
    lu_matrix = np.matrix(np.zeros([a.shape[0], a.shape[1]]))
    n = a.shape[0]

    for k in range(n):
        # calculate all residual k-row elements
        for j in range(k, n):
            lu_matrix[k, j] = a[k, j] - lu_matrix[k, :k] * lu_matrix[:k, j]
        # calculate all residual k-column elements
        for i in range(k + 1, n):
            lu_matrix[i, k] = (a[i, k] - lu_matrix[i, : k] * lu_matrix[: k, k]) / lu_matrix[k, k]

    return lu_matrix

In [162]:
def get_L(m):
    """Get triangular L matrix from a single LU-matrix
    :param m: numpy LU-matrix
    :return: numpy triangular L matrix
    """
    L = m.copy()
    for i in range(L.shape[0]):
        L[i, i] = 1
        L[i, i+1 :] = 0
    return np.matrix(L)

а)$$\begin{pmatrix} 1 & 2 & 4 \\ 2 & 9 & 12 \\ 3 & 26 & 30 \end{pmatrix}$$

In [163]:
A =np.array([[1, 2, 4],
             [2, 9, 12],
             [3, 26, 30]])
get_L(decompose_to_LU(A))

matrix([[1., 0., 0.],
        [2., 1., 0.],
        [3., 4., 1.]])

б)$$\begin{pmatrix} 1 & 1 & 2 & 4\\ 2 & 5 & 8 & 9\\ 3 & 18 & 29 & 18\\ 4 & 22 & 53 & 33 \end{pmatrix}$$

In [164]:
A =np.array([[1, 1, 2, 4],
             [2, 5, 8, 9],
             [3, 18, 29, 18],
             [4, 22, 53, 33]])
get_L(decompose_to_LU(A))

matrix([[1., 0., 0., 0.],
        [2., 1., 0., 0.],
        [3., 5., 1., 0.],
        [4., 6., 7., 1.]])

### Задача 3
Решить систему линейных уравнений методом $LU$$LU$-разложения

$$\begin{cases} 2x_{1}+x_{2}+3x_{3}=1 \\ 11x_{1}+7x_{2}+5x_{3}=-6 \\ 9x_{1}+8x_{2}+4x_{3}=-5 \end{cases}$$


In [165]:
A =np.array([[2, 1, 3],
             [11, 7, 5],
             [9, 8, 4]])

b = np.matrix([1, -6, -5]).T

LU = decompose_to_LU(A)
solve_LU(LU, b).T

matrix([[-1.,  0.,  1.]])

### Задача 4
Решить систему линейных уравнений методом Холецкого

$$\begin{cases} 81x_{1}-45x_{2}+45x_{3}=531 \\ -45x_{1}+50x_{2}-15x_{3}=-460 \\ 45x_{1}-15x_{2}+38x_{3}=193 \end{cases}$$

In [166]:
A =np.array([[81, -45, 45],
             [-45, 50, -15],
             [45, -15, 38]])

b = np.array([531, -460, 193])

In [167]:
lu_matrix = np.linalg.cholesky(A)
lu_matrix

array([[ 9.,  0.,  0.],
       [-5.,  5.,  0.],
       [ 5.,  2.,  3.]])

In [168]:
y1 = 531 / 9
y2 = (-460 + 5 * y1)/5
y3 = (193 - 5 * y1 -2 * y2)/3

In [169]:
lu_matrix.T

array([[ 9., -5.,  5.],
       [ 0.,  5.,  2.],
       [ 0.,  0.,  3.]])

In [170]:
x3 = y3 / 3
x2 = (y2 - 2 * x3) / 5
x1 = (y1 - 5 * x3 + 5 * x2)/9

print(f'{x1} {x2} {x3}')

6.0 -5.0 -4.0
