In [80]:
import numpy as np

### Задача 1
Решить систему уравнений методом Гаусса:

$$\begin{cases} x_{1}+x_{2}-x_{3}-2x_{4}=0, \\ 2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\ x_{1}+x_{2}-3x_{3}+x_{4}=4. \end{cases}$$

In [81]:
# т.к. ранги матрицы и расширенной матрицы совпадают, но отличаются от числа неизвестных, то система будет иметь бесконечное количество решений

a1 = np.array([1, 1, -1, -2, 0])
a2 = np.array([2, 1, -1, 1, -2])
a3 = np.array([1, 1, -3, 1, 4])
a1

array([ 1,  1, -1, -2,  0])

In [82]:
a2_ = a2 - a1 * 2
a2_

array([ 0, -1,  1,  5, -2])

In [83]:
a3_ = a3 - a1
a3_

array([ 0,  0, -2,  3,  4])

x4 - делаем параметром и для простоты приравниваем к 1

In [84]:
x4 = 1
x3 = (4 - 3 * x4) / (-2)
x2  = 2 + x3 + 5 * x4
x1 = -x2 + x3 + 2 * x4

print(f'Частное решение для СЛАУ')
print(f'x1 = {x1}\nx2 = {x2}\nx3 = {x3}\nx4 = {x4}\n')

Частное решение для СЛАУ
x1 = -5.0
x2 = 6.5
x3 = -0.5
x4 = 1



### Задача 2
Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

In [85]:
def kron_kop(base_m, free_members):
    A = base_m
    A_ = np.c_[A, free_members.T]

    rankA = np.linalg.matrix_rank(base_m)
    rankA_ = np.linalg.matrix_rank(A_)
    n = A.shape[1]

    if rankA != rankA_ :
        print('Система несовместна, решений нет')
    elif rankA == n:
        print('Система совместна и определена (имеет одно решение)')
    else:
        print('Система совместна и имеет бесконечное количество решений')

# 1) если  rankA=rankA~=n , где  n  — число неизвестных, то система определена, т. е. имеет единственное решение;
# 2) если  rankA=rankA~<n , то система имеет бесконечное количество решений;
# 3) если  rankA<rankA~ , то система несовместна.

а) $\begin{cases} 3x_{1}-x_{2}+x_{3}=4, \\ 2x_{1}-5x_{2}-3x_{3}=-17, \\ x_{1}+x_{2}-x_{3}=0; \end{cases}$

In [86]:
A = np.array([[3, -1, 1],
              [2, -5, -3],
              [1, 1, -1]])
b = np.array([4, -17, 0])
kron_kop(A, b)

Система совместна и определена (имеет одно решение)


б) $\begin{cases} 2x_{1}-4x_{2}+6x_{3}=1, \\ x_{1}-2x_{2}+3x_{3}=-2, \\ 3x_{1}-6x_{2}+9x_{3}=5; \end{cases}$

In [87]:
A = np.array([[2, -4, 6],
              [1, -2, 3],
              [3, -6, 9]])
b = np.array([1, -2, 5])
kron_kop(A, b)

Система несовместна, решений нет


в) $\begin{cases} x_{1}+2x_{2}+5x_{3}=4, \\ 3x_{1}+x_{2}-8x_{3}=-2. \end{cases}$

In [88]:
A = np.array([[1, 2, 5],
              [3, 1, -8]])
b = np.array([4, -2])
kron_kop(A, b)

Система совместна и имеет бесконечное количество решений


### Задача 3
Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix} \left.\begin{matrix} 1 & 3 & -2 & 4\\ 0 & 5 & 0 & 1\\ 0 & 0 & 3 & 0\\ 0 & 0 & 0 & 2 \end{matrix}\right| \begin{matrix} 3\\ 2\\ 4\\ 1 \end{matrix} \end{pmatrix}.$$

In [89]:
A = np.array([[1, 3, -2, 4],
              [0, 5, 0, 1],
              [0, 0, 3, 0],
              [0, 0, 0, 2]])
b = np.array([3, -2, 4, 1])
kron_kop(A, b)

Система совместна и определена (имеет одно решение)


### Задача 4
Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix} \left.\begin{matrix} 1 & 2 & 3\\ 4 & 5 & 6\\ 7 & 8 & 9 \end{matrix}\right| \begin{matrix} a\\ b\\ c \end{matrix} \end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

In [90]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.linalg.matrix_rank(A)

2

т.к. система является не совместной если не совпадают ранги матрицы и расширенной матрицы, а ранг матрицы равен 2, то система будет несовместной если
1) все три параметра отличны от нуля
2) два из трех параметров равны 0